(function(g){var window=this;'use strict';var csb=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.Jgb)("0",Math.max(0,b-c))+a},dsb=function(){return{I:"svg",
Y:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",Y:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},esb=function(){return{I:"svg",
Y:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",Y:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},gsb=function(a){"number"===typeof a?(this.date=fsb(a,0,1),A6(this,1)):g.cb(a)?(this.date=fsb(a.getFullYear(),a.getMonth(),a.getDate()),A6(this,a.getDate())):(this.date=new Date(g.ob()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),A6(this,a))},fsb=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},A6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},B6=function(a,b){g.HU.call(this,a,{I:"div",
S:"ytp-reminder-menu",Y:{role:"menu",tabindex:"-1"},V:[{I:"div",S:"ytp-reminder-menu-contents",V:[{I:"div",S:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Ia("ytp-reminder-menu-items");this.hide()},isb=function(a){var b=hsb(a),c=0;
c=0;for(var d={};c<b.length;d={FX:void 0},c++){var e=a.j[c];e||(e=new g.V({I:"div",S:"ytp-reminder-menu-item",Y:{role:"menuitem",tabindex:"0"},V:[{I:"div",S:"ytp-reminder-menu-item-icon",ya:"{{icon}}"},{I:"div",S:"ytp-reminder-menu-item-label",ya:"{{text}}"}]}),d.FX=c,e.Ta("click",function(h){return function(){var l=h.FX;a.Qb();l=hsb(a)[l];a.oa("reminderMenuItemClicked",l.serviceEndpoint||l.command)}}(d)),e.Ja(a.items),a.j[c]=e);
var f=b[c];d=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":d=dsb();break;case "NOTIFICATIONS_NONE":d=esb();break;case "NOTIFICATIONS_ACTIVE":d=g.vwa()}f=f.text?g.pG(f.text):"";e.update({icon:d,text:f})}for(;c<a.j.length;)a.j.pop().dispose();0===c?a.Qb():a.xd(a.buttonElement)},hsb=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},C6=function(a){g.V.call(this,{I:"div",
V:[{I:"button",La:["ytp-offline-slate-button","ytp-button"],V:[{I:"div",S:"ytp-offline-slate-button-icon",ya:"{{icon}}"},{I:"div",S:"ytp-offline-slate-button-text",ya:"{{text}}"}]}]});this.J=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.B=void 0;this.D=this.j=null;(this.buttonElement=this.Ia("ytp-offline-slate-button"))&&this.T(this.buttonElement,"click",this.G);this.hide()},ksb=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.U(c,jsb)?a.upcomingEventReminderButtonRenderer=g.U(c,jsb):c&&g.U(c,jsb)||(a.upcomingEventReminderButtonRenderer=null);D6(a)},D6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.pG(b.toggledText):"";a.update({text:c,icon:lsb(b.toggledIcon)})}else c=b.defaultText?g.pG(b.defaultText):"",a.update({text:c,icon:lsb(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=msb(a))?(c=b.text?g.pG(b.text):"",a.update({text:c,icon:lsb(b.icon)}),a.show()):a.hide():a.hide()},osb=function(a,b,c){a.D||(a.D=new g.DE(a.J.U().ql));
var d={context:g.Wra(a.D.config_||g.dE())};g.CF()&&(d.context.clientScreenNonce=g.CF());d.params=c;g.EE(a.D,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.B&&(a.upcomingEventReminderButtonRenderer.currentState=a.B,a.B=void 0)},
onError:function(){nsb(a)},
onTimeout:function(){nsb(a)}})},nsb=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,D6(a)):a.upcomingEventReminderButtonRenderer&&(a.B=void 0,D6(a))},lsb=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return dsb();case "NOTIFICATIONS_NONE":return esb();case "NOTIFICATIONS_ACTIVE":return g.vwa();default:return null}},msb=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.B||a.upcomingEventReminderButtonRenderer.currentState;a=g.u(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.U(c.value,psb))&&c.state===b&&c.button&&g.U(c.button,g.VM))return g.U(c.button,g.VM);return null},qsb=function(a){g.V.call(this,{I:"div",
S:"ytp-offline-slate",V:[{I:"div",S:"ytp-offline-slate-background"},{I:"div",S:"ytp-offline-slate-bar",V:[{I:"span",S:"ytp-offline-slate-icon",V:[{I:"svg",Y:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},V:[{I:"path",Y:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{I:"circle",Y:{cx:"12",cy:"12",r:"3"}}]}]},{I:"span",S:"ytp-offline-slate-messages",V:[{I:"div",S:"ytp-offline-slate-main-text",Y:{"aria-label":"{{label}}"},ya:"{{mainText}}"},{I:"div",S:"ytp-offline-slate-subtitle-text",ya:"{{subtitleText}}"}]},{I:"span",S:"ytp-offline-slate-buttons"}]},{I:"button",La:["ytp-offline-slate-close-button","ytp-button"],V:[g.sG()]},{I:"button",La:["ytp-offline-slate-open-button","ytp-button"],V:[g.rG()]}]});var b=this;this.api=a;this.j=this.B=null;this.background=this.Ia("ytp-offline-slate-background");
this.C=this.Ia("ytp-offline-slate-bar");this.G=new g.Qu(function(){g.Yu(b.C,"ytp-offline-slate-bar-fade")},15E3);
this.K=!1;this.D=new g.Qu(function(){g.Yu(b.element,"ytp-offline-slate-collapsed")},15E3);
g.N(this,this.D);g.N(this,this.G);this.countdownTimer=new g.Qu(this.E0,1E3,this);this.T(a,"presentingplayerstatechange",this.I0);this.T(a,"livestatedata",this.Sa);a=this.Ia("ytp-offline-slate-close-button");this.T(a,"click",function(){g.Yu(b.element,"ytp-offline-slate-collapsed")});
a=this.Ia("ytp-offline-slate-open-button");this.T(a,"click",function(){g.$u(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Sa(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().Pl;var c=8===this.api.getPresentingPlayerType();g.bv(this.element,"ytp-offline-slate-premiere-trailer",a);g.bv(this.element,"ytp-offline-slate-hide-background",c)},rsb=function(a,b,c){if(b){var d=null!=b.subtitleText?g.pG(b.subtitleText):"";
c=c?c:null!=b.mainText?g.pG(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.bv(a.element,"ytp-offline-slate-single-text-line",!d);g.bv(a.C,"ytp-offline-slate-bar-hidden",!c&&!d)}},E6=function(a,b){var c=(0,g.CD)();
this.module="heartbeat";this.trigger=a;this.j=b;this.C=c},zsb=function(a){g.OV.call(this,a);
var b=this;this.N=!1;this.Z=0;this.G=!1;this.B=new g.Qu(function(){var e=b.player.U(),f=b.getVideoData();F6(b)&&(ssb(b)?tsb(b,e,f):(usb(b),vsb(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.D=!1;this.K=new g.Cl(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.ma=new g.DE(void 0);this.X=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new gsb).getTimezoneOffset();this.C=new g.UK(this);g.N(this,this.B);g.N(this,this.C);usb(this);wsb(this);this.C.T(a,"heartbeatparams",this.DE);this.C.T(a,"presentingplayerstatechange",this.s2);this.C.T(a,"videoplayerreset",this.t2);this.C.T(a,g.hK("heartbeat"),this.onCueRangeEnter);this.D&&this.j&&
xsb(this,void 0,this.j);var c=new g.gK(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.gK(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.xf([c,d]);ysb(this)},ysb=function(a){var b=a.getVideoData();
b.Nm&&(b=b.botguardData)&&g.GMa(b,a.player.U())},usb=function(a){var b=a.getVideoData();
if(b.Nm&&(b=new g.CMa(b),g.rI.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.Mk){var d=g.DMa(b);if(d){c={};var e={};d=d.split("&");d=g.u(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=Asb[Number(e.r1c)]);c.challenge=b.videoData.Mk}}a.attestationResponse=c||void 0}},ssb=function(a){var b=a.getVideoData();
if(!g.CT(a.getVideoData())||b.MY)return!1;if(b.useInnertubeDrmService()&&b.K){a="playready"===b.K.flavor&&b.L("html5_innertube_heartbeats_for_playready");var c="widevine"===b.K.flavor&&b.L("html5_innertube_heartbeats_for_widevine");b=g.DR(b.K)&&b.L("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},Bsb=function(a){if(ssb(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.CT(a.getVideoData())&&b.useInnertubeDrmService()&&!b.El&&!b.kC?!1:!!b.heartbeatToken},G6=function(a,b){if(!a.B.isActive()&&a.N){var c=a.getVideoData();
if(Bsb(a)||c.isLivePlayback){if(void 0===b)if(a.G)if(a.D)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().XX||6E4}else b=1E3;a.B.start(b)}}},Fsb=function(a,b,c){b.Vm&&(c=g.Nm(c,{internalipoverride:b.Vm}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.ub&&(d.kpt=b.ub);c=g.Nm(c,d);g.cC(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.B.isActive()&&F6(a)){a.K.reset();a.sequenceNumber++;e=e.responseText;var f=Csb(e);if(f){a.player.kb("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(Dsb))?"0"===h[1]?0:1:-1;Esb(a,void 0,f,e,h)}},
onError:function(e){F6(a)&&H6(a,!0,"net-"+e.status)},
onTimeout:function(){F6(a)&&H6(a,!0,"timeout")},
withCredentials:!0})},tsb=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.Nm(a.heartbeatParams.url,{request_id:g.sta()});c.Ba&&(e=g.Nm(e,{vvt:c.Ba}),c.mdxEnvironment&&(e=g.Nm(e,{mdx_environment:c.mdxEnvironment})));g.CS(b,c.oauthToken).then(function(f){f&&(e=g.Nm(e,{access_token:f}));Fsb(a,c,e)})}},F6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.VG(a.player.Ub(a.getPlayerType()),4)?!1:Bsb(a)||b.isLivePlayback?!0:(I6(a),!1)},vsb=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.qa)?d:c.heartbeatServerData};a.X=a.attestationResponse;c.Nm&&(e.attestationResponse=a.X);var f=g.cU(c),h;d=null!=(h=f.client)?h:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=h;h={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.JJ(b)){h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=Gsb(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.Cb())?void 0:g.bW(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});h.unpluggedParams=d}e.heartbeatRequestParams=
h;c.isLivePlayback?(l=Gsb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l})):b.L("enable_heartbeat_vod_playback_position")&&(l=Hsb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={streamTimeMillis:l}));a.player.oa("heartbeatRequest",e);var n={timeout:3E4,onSuccess:function(p){if(!a.B.isActive()&&F6(a)){var q=a.getVideoData(),r=q.Nm&&null==a.X,t;q.Nm=!(null==(t=p.heartbeatAttestationConfig)||!t.requiresAttestation)||
r;r=p.playabilityStatus;t=JSON.stringify(r)||"{}";p.authenticationMismatch&&a.player.va("authshear",{});var v=-1;var x=p.playabilityStatus;x&&(a.player.kb("onHeartbeat",x),"OK"===x.status?v=p.stopHeartbeat?2:0:"UNPLAYABLE"===x.status?v=1:"LIVE_STREAM_OFFLINE"===x.status&&(v=0));a.sequenceNumber&&-1===v||a.K.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.qa=p.heartbeatServerData);q.mC=p;(x=p.playerCueRangeSet)&&g.vSa(q,x);p.playerCueRanges&&0<p.playerCueRanges.length&&(q.cueRanges=p.playerCueRanges);
var B,E;(null==(B=p.progressBarConfig)?0:B.progressBarStartPosition)&&(null==(E=p.progressBarConfig)?0:E.progressBarEndPosition)&&(q.progressBarStartPosition=p.progressBarConfig.progressBarStartPosition,q.progressBarEndPosition=p.progressBarConfig.progressBarEndPosition);q.compositeLiveIngestionOffsetToken=p.compositeLiveIngestionOffsetToken;p.compositeLiveStatusToken!==q.compositeLiveStatusToken&&(q.compositeLiveStatusToken=p.compositeLiveStatusToken);q.oa("dataupdated");Esb(a,p,r,t,v)}},
onError:function(p){F6(a)&&H6(a,!0,"net-"+p.status)},
onTimeout:function(){F6(a)&&H6(a,!0,"timeout")}};
g.CS(b,g.UT(c)).then(function(p){p&&(n.hV="Bearer "+p);g.EE(a.ma,"player/heartbeat",e,n)})},Esb=function(a,b,c,d,e){-1===e?(c="decode "+g.wg(d,3),H6(a,!1,c)):2===e?(I6(a),a.G=!0):(a.Z=0,a.B.stop(),1===e?(a.G=!1,c&&"PLAYABILITY_ERROR_CODE_EMBARGOED"===c.errorCode&&a.player.oo(!0),e="",a.player.U().L("html5_log_playability_reason")&&(e="pe."+(null==c?void 0:c.errorCode)+";ps."+(null==c?void 0:c.status)),a.player.Bg("heartbeat.stop",2,a.yf(d),e),g.nD("heartbeatActionPlayerHalted",Isb(c)),(null==b?0:
b.videoTransitionEndpoint)&&c&&(b=b.videoTransitionEndpoint,(d=g.U(b,g.rT))&&Jsb(a,d,c,{itct:null==b?void 0:b.clickTrackingParams}))):(a.G=!0,d=0,a.D&&c&&(d=xsb(a,b,c),a.player.oa("livestatedata",c)),d?G6(a,d):G6(a)))},xsb=function(a,b,c){var d=c.liveStreamability&&c.liveStreamability.liveStreamabilityRenderer,e=!(!d||!(d.switchStreamsImmediately||d.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===d.transitionTiming));
b=Ksb(a,b,d);var f=a.getVideoData(),h=a.player.Ub(a.getPlayerType()),l=h.isPlaying()&&!g.IT(f)&&!a.player.isAtLiveHead(a.getPlayerType());if(f.U().Qc()){var m,n=(null==(m=a.player.sf())?void 0:m.pc())||{};n.status=c.status||"";n.dvr=""+ +l;n["switch"]=""+ +e;n.ended=""+ +!(!d||!d.displayEndscreen);a.player.va("heartbeat",n)}if(l&&!e)return b;e=d&&d.streamTransitionEndpoint&&g.U(d.streamTransitionEndpoint,g.rT);if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(d&&d.transitionTiming))a.getVideoData().transitionEndpointAtEndOfStream=
e;else if(e&&Jsb(a,e,c))return b;if("OK"===c.status.toUpperCase()){e=d&&d.broadcastId;m=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;l=e!==m&&null!=e;if(!g.FT(f)||l){var p={video_id:f.videoId};f.tC&&(p.is_live_destination="1");a.player.L("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.getWatchNextResponse());p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;
p.force_gvi=f.Um;p.zm=f.zm;f.G&&(p.vss_credentials_token=f.G,p.vss_credentials_token_type=f.Lm);f.Ba&&(p.vvt=f.Ba);d=void 0;g.FT(f)?l&&(d=new E6("broadcastIdChanged",m+","+e),a.VI("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",c)):(e&&(d=new E6("formatsReceived",""+e)),a.VI("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",c));a.player.loadVideoByPlayerVars(p,void 0,void 0,void 0,d);return b}a.player.Ng("heartbeat",
a.getPlayerType())}d&&d.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.K=!0,a.Gb&&a.api.mB()):g.PL(h)&&(f=(null==(p=a.player.sf())?void 0:p.pc())||{},a.player.va("hbse",f,!0),a.player.mB(),a.player.kb("onLiveMediaEnded",c)));return b},Ksb=function(a,b,c){return a.player.L("web_player_use_heartbeat_poll_delay_ms")&&(a=Number(null==b?void 0:b.pollDelayMs))?a:(c=Number(null==c?void 0:c.pollDelayMs))?c:0},H6=function(a,b,c){var d=a.player.U();
if(!a.B.isActive()){a.B.stop();a.Z++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.kY||b&&!g.CT(a.getVideoData())&&!Bsb(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.retries)?h=a.heartbeatParams.retries:h=f.YX||5;f=a.Z>=h}f?(g.nD("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:Isb()),(b=a.getVideoData())&&b.isLivePlayback?a.player.Bg(e,1,"Reprodu\u00e7\u00e3o de v\u00eddeo interrompida. Tente novamente.",c):a.player.Bg(e,
1,"Ocorreu um erro ao licenciar este v\u00eddeo.",c)):(d.L("html5_report_non_fatal_heartbeat_error")&&a.player.Hr(e,{msg:c}),G6(a,a.K.getValue()),g.Dl(a.K))}},Isb=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},I6=function(a){a.Z=0;
a.B.stop();a.G=!1;a.sequenceNumber=0},wsb=function(a){var b=a.getVideoData(),c=a.player.U();
if(b.isLivePlayback)if(g.eQa(c.G)){a.D=!0;a.N=!0;if(!g.LJ(c)||g.JJ(c))a.offlineSlate=new qsb(a.player),g.N(a,a.offlineSlate),g.zU(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;"UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)&&(a.j?(d=Ksb(a,void 0,a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?G6(a,d):G6(a,7500):G6(a,1E3))}else a.player.Bg("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.Gb(b.Ga,"heartbeat")&&a.player.Ng("heartbeat",a.getPlayerType())},Jsb=function(a,b,c,d){var e=b&&b.videoId;
return e?(a.player.Io(e,Object.assign({},{autonav:"1"},d||{}),void 0,!0,!0,b,g.UT(a.getVideoData())),a.VI("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",c),!0):!1},Gsb=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},Hsb=function(a){return(a=a.player.getCurrentTime(a.getPlayerType()))&&isFinite(a)?""+Math.floor(1E3*a):null},Csb=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},Lsb={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
Lsb={ERAS:["a.C.","d.C."],ERANAMES:["antes de Cristo","depois de Cristo"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),STANDALONEMONTHS:"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),SHORTMONTHS:"jan. fev. mar. abr. mai. jun. jul. ago. set. out. nov. dez.".split(" "),STANDALONESHORTMONTHS:"jan. fev. mar. abr. mai. jun. jul. ago. set. out. nov. dez.".split(" "),
WEEKDAYS:"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),STANDALONEWEEKDAYS:"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),SHORTWEEKDAYS:"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),STANDALONESHORTWEEKDAYS:"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),NARROWWEEKDAYS:"DSTQQSS".split(""),STANDALONENARROWWEEKDAYS:"DSTQQSS".split(""),SHORTQUARTERS:["T1","T2","T3","T4"],QUARTERS:["1\u00ba trimestre",
"2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, d 'de' MMMM 'de' y","d 'de' MMMM 'de' y","d 'de' MMM 'de' y","dd/MM/y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{1} '\u00e0s' {0}","{1} '\u00e0s' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
var Asb=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"];g.k=gsb.prototype;g.k.oW=Lsb.FIRSTDAYOFWEEK;g.k.pW=Lsb.FIRSTWEEKCUTOFFDAY;g.k.clone=function(){var a=new gsb(this.date);a.oW=this.oW;a.pW=this.pW;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.years||a.months){var b=this.getMonth()+a.months+12*a.years,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),A6(this,a.getDate()))};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+csb(Math.abs(a),b?6:4),csb(this.getMonth()+1,2),csb(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var Msb=new g.Fw("addUpcomingEventReminderEndpoint");var Nsb=new g.Fw("removeUpcomingEventReminderEndpoint");var Osb=new g.Fw("updateUpcomingEventReminderButtonStateCommand");var jsb=new g.Fw("upcomingEventReminderButtonRenderer"),psb=new g.Fw("upcomingEventReminderButtonStateRenderer");g.w(B6,g.HU);B6.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.HU.prototype.hide.call(this)};
B6.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.HU.prototype.show.call(this)};
B6.prototype.xa=function(){g.wb(this.j);g.HU.prototype.xa.call(this)};g.w(C6,g.V);
C6.prototype.G=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.C(a.toggledServiceEndpoint):this.C(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;D6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.Gb)this.j.Qb();else{var b=msb(this);b&&this.C(b.serviceEndpoint||b.command);b=(null==(a=g.U(null==b?void 0:b.command,g.ZG))?void 0:a.commands)||[];a:{a=g.u(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=null==(b=g.U(c.value,
g.tib))?void 0:null==(d=b.popup)?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new B6(this.J,this.buttonElement),this.j.Ja(this.element),g.N(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.C,this));b=this.j;b.menuPopupRenderer=a;isb(b)}};
C6.prototype.C=function(a){var b=g.U(a,Msb),c=g.U(a,Nsb);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(osb(this,e,d.params),a=g.u(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.U(b,Osb)){this.B=g.U(b,Osb).state;D6(this);break}}};g.w(qsb,g.V);g.k=qsb.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Sa=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.B=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.E0():rsb(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new C6(this.api),this.j.Ja(this.Ia("ytp-offline-slate-buttons")),g.N(this,this.j)),ksb(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&ksb(this.j,null,null);this.B=a}else this.B=null;this.I0()};
g.k.I0=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Ub(),d=this.getVideoData();b=d.isLivePlayback&&(g.PL(c)||g.VG(c,2)||g.VG(c,64));var e=2===d.autonavState&&g.VG(c,2);c=c.isPlaying()&&!g.IT(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.B?this.Gb?(null==a?0:g.XG(a,2))&&!this.getVideoData().Pl&&(g.$u(this.element,"ytp-offline-slate-collapsed"),this.D.stop(),g.$u(this.C,"ytp-offline-slate-bar-fade"),this.G.start()):(this.show(),this.D.start(),this.api.oa("offlineslatestatechange"),
this.K&&this.api.mB()):this.Gb&&(this.hide(),this.api.oa("offlineslatestatechange"))};
g.k.E0=function(){var a,b,c,d,e=null==(a=this.B)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.ob()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(rsb(this,e),this.countdownTimer.stop()):(rsb(this,e,g.eH(b-a)),g.Ru(this.countdownTimer)))};
g.k.xa=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.V.prototype.xa.call(this)};E6.prototype.B=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
E6.prototype.isExpired=function(){return 6E4<(0,g.CD)()-this.C};
E6.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.w(zsb,g.OV);g.k=zsb.prototype;g.k.xa=function(){I6(this);this.player.Cf("heartbeat");g.OV.prototype.xa.call(this)};
g.k.onCueRangeEnter=function(){this.N=!0;G6(this,2E3)};
g.k.DE=function(a){this.heartbeatParams=a;G6(this,2E3)};
g.k.s2=function(a){var b;8!==this.player.getPresentingPlayerType()&&"UNPLAYABLE"!==(null==(b=this.j)?void 0:b.status)&&(g.VG(a.state,2)||g.VG(a.state,64)?(I6(this),this.D&&(this.N=!0,G6(this,1E3))):(g.VG(a.state,1)||g.VG(a.state,8))&&G6(this,2E3))};
g.k.t2=function(){3!==this.player.getPresentingPlayerType()&&G6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.yl=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.VI=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.nD("heartbeatActionPlayerTransitioned",a)};
g.k.yf=function(a){var b="LICENSE",c=Csb(a);if(c)return c.reason||g.kW[b]||"";(a=a.match(Dsb))&&(a=Number(a[1]))&&(b=g.bCa(a));return g.kW[b]||""};
g.k.YD=function(){return!!this.offlineSlate&&this.offlineSlate.Gb};
var Dsb=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.NV("heartbeat",zsb);})(_yt_player);
